#!/usr/bin/env python3
"""
aggregate_sensitivity.py — build the Pycom sensitivity table (appendix).

Reads every cell of the pre-declared slice_len x augmentation grid produced by
run_sensitivity.sh and emits a LaTeX table reporting ALL cells.

The control cell (slice_len=288, base augmentation) reproduces the main-table
setting, so the reader can see how far each variation moves the result from
the configuration the paper actually uses. Deltas are shown against it.

No cell here belongs in a main table. Promoting the best one would mean Pycom
had been tuned while NEU was not.

Usage:
    python aggregate_sensitivity.py res_out_sensitivity --out tables/
"""

from __future__ import annotations

import argparse
import os
import re
import sys

CONTROL = ('288', 'base')

METRICS = [
    ('softmax_acc',      'Softmax'),
    ('traj_closed_acc',  'T2R closed'),
    ('traj_auroc',       'T2R AUROC'),
    ('knn_closed_acc',   '$k$-NN closed'),
]


def _last_pass(text: str) -> str:
    marks = [m.start() for m in re.finditer(r'^### Phase 4  started', text, re.M)]
    return text[marks[-1]:] if marks else text


def read_cell(path: str) -> dict | None:
    if not os.path.isfile(path):
        return None
    block = _last_pass(open(path).read())
    out = {}
    for key, _ in METRICS:
        m = re.search(rf'^  {re.escape(key)} = ([\d.eE+-]+)\s*$', block, re.M)
        if m:
            try:
                out[key] = float(m.group(1))
            except ValueError:
                pass
    return out or None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('base', help='res_out_sensitivity directory')
    ap.add_argument('--out', default='.', help='Where to write the table')
    a = ap.parse_args()

    if not os.path.isdir(a.base):
        print(f'No sensitivity directory: {a.base}', file=sys.stderr)
        return 1

    cells = {}
    for name in sorted(os.listdir(a.base)):
        m = re.fullmatch(r'sl(\d+)_(base|strong)', name)
        if not m:
            continue
        got = read_cell(os.path.join(a.base, name, 'results_phase4.txt'))
        if got:
            cells[(m.group(1), m.group(2))] = got

    if not cells:
        print(f'No completed sensitivity cells under {a.base}', file=sys.stderr)
        return 1

    ctrl = cells.get(CONTROL)
    os.makedirs(a.out, exist_ok=True)

    lines = [
        '% Pycom sensitivity analysis (appendix). Generated by',
        '% aggregate_sensitivity.py. Single seed; every cell reported.',
        '% The control cell is the main-table configuration.',
        '\\begin{tabular}{llcccc}',
        '\\toprule',
        'Slice & Aug. & ' + ' & '.join(lbl for _, lbl in METRICS) + ' \\\\',
        '\\midrule',
    ]

    hdr = f'{"slice":>6}{"aug":>9}' + ''.join(f'{lbl:>16}' for _, lbl in METRICS)
    print(hdr)
    print('-' * len(hdr))

    for (sl, aug) in sorted(cells, key=lambda t: (int(t[0]), t[1])):
        vals = cells[(sl, aug)]
        is_ctrl = (sl, aug) == CONTROL
        row = [sl, aug + (' (control)' if is_ctrl else '')]
        pr  = [f'{sl:>6}', f'{aug:>9}']
        for key, _ in METRICS:
            v = vals.get(key)
            if v is None:
                row.append('--'); pr.append(f'{"--":>16}'); continue
            cell = f'{v:.3f}'
            if ctrl and not is_ctrl and key in ctrl:
                d = v - ctrl[key]
                cell += f' ({d:+.3f})'
            row.append(f'\\textbf{{{cell}}}' if is_ctrl else cell)
            pr.append(f'{cell:>16}')
        lines.append(' & '.join(row) + ' \\\\')
        print(''.join(pr))

    lines += [
        '\\bottomrule',
        '\\end{tabular}',
        '',
        '% Chance closed-set accuracy is 0.0625 (1 of 16 devices).',
        '% Parenthesised values are the change from the control cell.',
    ]

    dest = os.path.join(a.out, 'pycom_sensitivity.tex')
    with open(dest, 'w') as f:
        f.write('\n'.join(lines))

    print(f'\nwrote {dest}')
    if ctrl is None:
        print('WARNING: control cell sl288_base is missing — deltas omitted.')
    print('Chance closed-set accuracy is 0.0625. Report every cell; do not '
          'promote one into a main table.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
